#!/usr/bin/python
#
# mdplot - Molecular Dynamics simulation plotter
#
# Copyright (C) 2008  Peter Colberg <peter.colberg@physik.uni-muenchen.de>
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301, USA.
#

import argparse
import tables
import matplotlib
# choose backend which does not require an X server
matplotlib.use('Agg')

from matplotlib import rc
from mdplot import perf, pdf, traj


# parse command line arguments
parser = argparse.ArgumentParser(prog='mdplot')
subparsers = parser.add_subparsers(dest='command', help='available plot modules')
perf.add_parser(subparsers)
pdf.add_parser(subparsers)
traj.add_parser(subparsers)
args = parser.parse_args()

# set matplotlib defaults
rc('font', family='serif', serif=['Computer Modern Roman'])
rc('text', usetex=True)

try:
    # execute plot command
    if args.command == perf.command:
        perf.plot(args)
    elif args.command == pdf.command:
        pdf.plot(args)
    elif args.command == traj.command:
        traj.plot(args)

except SystemExit, status:
    exit('ERROR: %s' % status)

