#!/usr/bin/python
#
# mdplot - Molecular Dynamics simulation plotter
#
# Copyright (C) 2008  Peter Colberg <peter.colberg@physik.uni-muenchen.de>
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301, USA.
#

import argparse
import tables
import matplotlib
# choose backend which does not require an X server
matplotlib.use('Agg')

from matplotlib import rc
from mdplot import *

def main():
    # parse command line arguments
    args = parse_args()

    # set matplotlib defaults
    rc('font', family='serif', serif=['Computer Modern Roman'])
    rc('text', usetex=True)
    if args.a4:
        rc('figure', figsize=[11.7, 8.3])

    # execute plot command
    try:
        for plot in plots:
            if args.command == plot.command:
                plot.plot(args)

    except SystemExit, status:
        exit('ERROR: %s' % status)


plots = (corr, en, perf, pdf, traj)

def parse_args():
    parser = argparse.ArgumentParser(prog='mdplot')
    parser.add_argument('--output', required=True, help='output filename')
    parser.add_argument('--a4', action="store_true", help='DIN A4 format')

    subparsers = parser.add_subparsers(dest='command', help='available plot modules')
    for plot in plots:
        plot.add_parser(subparsers)

    return parser.parse_args()


if __name__ == "__main__":
    main()

